services:

  alpine:
    build:
      context: .docker/${DOCKER_IMAGE_SOURCE}/
      dockerfile: alpine.Dockerfile
      args:
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
        DEV_IMAGE_TAG: ${DEV_IMAGE_TAG}
        PROD_IMAGE_TAG: ${PROD_IMAGE_TAG}
    networks:
      - default

networks:
  default:
    name: ${DOCKER_NETWORK}
    driver: bridge


